<div class="single-fixture-right-widget">
    <table class="table table-striped table-responsive">
        <thead>
            <tr>
                <th>team</th>
                <th>w</th>
                <th>d</th>
                <th>l</th>
                <th>pts</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Chelsea</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Aresenal</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Real Soccer</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Real Madrid</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>City Club</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Aresenal</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Real Soccer</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Real Madrid</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Chelsea</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Aresenal</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
            <tr>
                <td>Chelsea</td>
                <td>12</td>
                <td>03</td>
                <td>00</td>
                <td>54</td>
            </tr>
        </tbody>
    </table>
</div>